
name: disco-pipeline

on: [push, pull_request]

# ensure multiple CI processes are not running analysis on contracts
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true


env:
  CI: true
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}
  FORCE_COLOR: 2
  NODE_ENV: production


jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['14.x', '16.x']
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: yarn install
    - run: yarn run build

    - name: Test lint
      run: yarn lint

    - name: Publish build
      run: .github/scripts/release-build '${{ secrets.DEV_BUILD_GITHUB_TOKEN }}'
      if: ${{ github.event_name == 'push' }}
